-- Audit + error tables for the Oracle → Snowflake migration pipeline.
-- Run once per target Snowflake environment.

CREATE TABLE IF NOT EXISTS PROD_DB.CORTEX_CHAT_APP.MIGRATION_AUDIT_LOG (
    AUDIT_ID                NUMBER AUTOINCREMENT PRIMARY KEY,
    MAPPING_NAME            VARCHAR(256),
    PROCEDURE_NAME          VARCHAR(256),
    EXEC_START_TS           TIMESTAMP_NTZ,
    EXEC_END_TS             TIMESTAMP_NTZ,
    STATUS                  VARCHAR(32),
    ROWS_INSERTED           NUMBER,
    ROWS_UPDATED            NUMBER,
    ROWS_DELETED            NUMBER,
    SOURCE_ROW_COUNT        NUMBER,
    INFORMATICA_MAPPING_REF VARCHAR(256),
    ERROR_MESSAGE           VARCHAR,
    BATCH_ID                VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS PROD_DB.CORTEX_CHAT_APP.MIGRATION_ERROR_LOG (
    ERROR_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    PROC_NAME     VARCHAR(256),
    ERROR_CODE    VARCHAR(64),
    ERROR_MESSAGE VARCHAR,
    FAILED_SQL    VARCHAR,
    EXEC_TS       TIMESTAMP_NTZ,
    BATCH_ID      VARCHAR(64)
);
